context:
  name: strace
  version: "6.12"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/strace/strace/releases/download/v${{ version }}/${{ name }}-${{ version }}.tar.xz
  sha256: c47da93be45b6055f4dc741d7f20efaf50ca10160a5b100c109b294fd9c0bdfe

build:
  number: 0
  skip:
    - not linux
  script: |
    ./configure --prefix=$PREFIX \
        --disable-silent-rules \
        --enable-mpers=no

    make
    make install


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - make
    - pkg-config
  host:
    - kernel-headers_${{ target_platform }}

tests:
  - script:
      - strace --version
      - strace true 2>&1 | grep "execve("
      - strace true 2>&1 | grep "+++ exited with 0 +++"

about:
  homepage: https://strace.io/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Diagnostic, instructional, and debugging tool for the Linux kernel
  description: |
    strace is a diagnostic, debugging and instructional userspace utility for Linux.
    It intercepts and records the system calls which are called by a process and
    the signals which are received by a process.
  repository: https://github.com/strace/strace

extra:
  recipe-maintainers:
    - wolfv
